# Generated by Django 4.2.16 on 2024-10-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_project_user_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
