# Generated by Django 4.2.16 on 2024-10-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_document_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_type',
        ),
        migrations.AddField(
            model_name='document',
            name='file_extension',
            field=models.CharField(default='None', max_length=15),
            preserve_default=False,
        ),
    ]
