# Generated by Django 4.2.16 on 2024-10-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_remove_document_file_type_document_file_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='s3_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
