# Generated by Django 4.2.16 on 2024-10-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_alter_document_s3_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='s3_file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='project_user',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='documents', to='projectapp.keyword'),
        ),
    ]
