# Generated by Django 4.2.16 on 2024-11-02 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_keyword_alter_document_s3_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='project_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projectapp.project_group'),
        ),
        migrations.AddField(
            model_name='project_group',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to='projectapp.project_user'),
        ),
    ]
