# Generated by Django 4.2.16 on 2024-11-03 00:17
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0008_join_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='document_keywords', to='projectapp.keyword'),
        ),
        migrations.AlterField(
            model_name='project_user',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='project_users', to='projectapp.keyword'),
        ),
    ]
