# Generated by Django 4.2.16 on 2024-12-04 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0013_alter_task_due_date_alter_task_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
    ]
